export const ALL_COUNTRIES = 'ALL_COUNTRIES';
export const COUNTRY_BY_ID = 'COUNTRY_BY_ID';
export const GET_NAME_COUNTRY = 'GET_NAME_COUNTRY';
export const ORDER_AND_FILTER = 'ORDER_AND_FILTER';
export const POST_ACTIVITY = 'POST_ACTIVITY';
export const STATE_NULL = 'STATE_NULL';

